# This is a basic example of a caller workflow

name: Code Scanning - Reusable Workflow

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '17 19 * * 6'
    
jobs:
  # Reference the reusable workflow
  security-scanning:
    uses: leftrightleft/example-workflows/.github/workflows/reusable-code-scanning.yml@main
    with:
      languages: "[ 'go', 'python' ]"
      build-command: "echo 'helllo'"
